# Generated by Django 3.1.6 on 2021-06-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('nombreCliente', models.CharField(max_length=20)),
                ('apellidoCliente', models.CharField(max_length=20)),
                ('fechaCreacion', models.CharField(max_length=20)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
